platform :ios, '8.1'
#pod 'AsyncImageView', '~> 1.5.1'
pod 'Nimbus/AttributedLabel', '~> 1.0.0'
pod 'JSONModel', '~> 0.10.0'
#pod 'FMDB'
pod 'MBProgressHUD'
#pod 'AKTabBarController'
pod 'SDWebImage'
